### PR TITLE
[bugfix] fix for template_type attribute change check in mso_schema r…

### LINKED ISSUE #232: Updating a sub-attribute of a template in `mso_schema` fails when `template_type` is not specified in the Terraform config.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/ciscodevnet/mso v0.11.0

### MSO version

* NDO V 4.1.2e

### Affected Resource(s)

* mso_schema

### Expected Behavior

When a `description` attribute is added to an existing template in a `mso_schema` resource, the description will be updated.

### Actual Behavior

The provider attempts to remove and create a replacement template block.

Note: This also applies when adding new template blocks to an existing `mso_schema` resource.

### Steps to Reproduce

1. Define the schema with one template and no description:

```hcl
resource "mso_schema" "schema" {
    name = "Bug"

    template {
        name          = "Template1"
        display_name  = "Template1"
        tenant_id     = "64b8e6f789c60aeac323c7c5"
    }
}
```

2. `terraform apply`

3. Update the template to include a description:

```hcl
resource "mso_schema" "schema" {
    name = "Bug"

    template {
        name          = "Template1"
        display_name  = "Template1"
        tenant_id     = "64b8e6f789c60aeac323c7c5"
        description   = "bug"
    }
}
```

4. `terraform plan`

```
  # module.ndo.mso_schema.schema will be updated in-place
  ~ resource "mso_schema" "schema" {
        id   = "64b8e6fa89c60aeac323c7c8"
        name = "Bug"

      - template {
          - display_name  = "Template1" -> null
          - name          = "Template1" -> null
          - template_type = "aci_multi_site" -> null
          - tenant_id     = "64b8e6f789c60aeac323c7c5" -> null
        }
      + template {
          + description   = "bug"
          + display_name  = "Template1"
          + name          = "Template1"
          + template_type = (known after apply)
          + tenant_id     = "64b8e6f789c60aeac323c7c5"
        }
    }
```

### PR DESCRIPTION
**Pull request by akinross**
…esource when not template_type is not specified and other attributes like description are changed

fixes #232

### CODE REVIEW

File: mso/resource_mso_schema.go [hunk 1]
```diff
@@ -375,7 +375,11 @@ func resourceMSOSchemaUpdate(d *schema.ResourceData, m interface{}) error {
 				for _, valueMapNew := range getDifferenceNew {
 					valueNew := valueMapNew.(map[string]interface{})
 					if valueOld["name"] == valueNew["name"] && valueOld["template_type"] != valueNew["template_type"] {
-						return fmt.Errorf("Template type cannot be changed.")
+						// Conditional to check if template type configured is aci_multisite and template type not provided
+						// This conditional is added to handle default behaviour when template type is not provided
+						if valueNew["template_type"] != "" && valueOld["template_type"] == "aci_multisite" {
```
Comment (shrsr) [inline mso/resource_mso_schema.go:380]: if valueNew["template_type"] != "" && valueOld["template_type"] == "aci_multisite" -> if valueNew["template_type"] != "" && valueOld["template_type"] == "aci_multi_site"

File: mso/resource_mso_schema.go [hunk 2]
```diff
@@ -375,7 +375,11 @@ func resourceMSOSchemaUpdate(d *schema.ResourceData, m interface{}) error {
...
+							return fmt.Errorf("Template type cannot be changed.")
```
Comment (shrsr) [inline mso/resource_mso_schema.go:381]: Are we allowing the user to change the template_type for other scenarios apart from the above condition?

**Review by shrsr — CHANGES_REQUESTED** [review]

File: mso/resource_mso_schema.go (hunk 1 above)
Comment (akinross) [reply mso/resource_mso_schema.go:380]: you are correct

File: mso/resource_mso_schema.go (hunk 2 above)
Comment (akinross) [reply mso/resource_mso_schema.go]: adjusted by leveraging default since that wil remove the need of complex conditionals which in the end amount to same thing

**Review by anvitha-jain — DISMISSED** [review]
LGTM

**Review by sajagana — DISMISSED** [review]
LGTM!

**Review by shrsr — CHANGES_REQUESTED** [review]
Failing idempotency when description is changed (at least as a cosmetic mannerism)

**Review by anvitha-jain — APPROVED** [review]

**Review by sajagana — APPROVED** [review]
LGTM!

**Review by shrsr — APPROVED** [review]
LGTM!!

**Review by lhercot — APPROVED** [review]
LGTM
