### PR TITLE
[bugfix] Fix fex and micro_seg_vlan attributes in resource_mso_schema_site_anp_epg_bulk_staticport to be correctly set when index shift occur in the static_ports list (DCNE-223)

### LINKED ISSUE #311: mso_schema_site_anp_epg_bulk_staticport doesnt update fex field correctly (DCNE-223)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.7.3

### MSO version

* V 4.2.3k

### APIC version and APIC Platform for Site Level Resources

* V 5.2

### Affected Resource(s)

* mso_schema_site_anp_epg_bulk_staticport

### Terraform Configuration Files

```hcl
resource "mso_schema_site_anp_epg_bulk_staticport" "static_port" {
    anp_name      = "PROD_AP"
    epg_name      = "EPG1"
    schema_id     = "66b61b98cecea29623726b33"
    site_id       = "616062f8e2a0c43c4efe1bf7"
    template_name = "E1"


    static_ports {
        deployment_immediacy = "lazy"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/8"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }

    #static_ports {
    #    deployment_immediacy = "lazy"
    #    leaf                 = "101"
    #    micro_seg_vlan       = 0
    #    fex                  = "101"
    #    mode                 = "regular"
    #    path                 = "eth1/21"
    #    path_type            = "port"
    #    pod                  = "pod-1"
    #    vlan                 = 1000
    #}

    static_ports {
        deployment_immediacy = "lazy"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/12"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }

    static_ports {
        deployment_immediacy = "lazy"
        leaf                 = "101"
        micro_seg_vlan       = 0
        fex = "101"
        mode                 = "regular"
        path                 = "eth1/21"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }

    static_ports {
        deployment_immediacy = "lazy"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/9"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }
}
```

### Debug Output

```
resource "mso_schema_site_anp_epg_bulk_staticport" "static_port" {
    anp_name      = "PROD_AP"
    epg_name      = "EPG1"
    id            = "66b61b98cecea29623726b33/site/616062f8e2a0c43c4efe1bf7/template/E1/anp/PROD_AP/epg/EPG1"
    schema_id     = "66b61b98cecea29623726b33"
    site_id       = "616062f8e2a0c43c4efe1bf7"
    template_name = "E1"

    static_ports {
        deployment_immediacy = "lazy"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/8"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }
    static_ports {
        deployment_immediacy = "lazy"
        fex                  = "101"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/21"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }
    static_ports {
        deployment_immediacy = "lazy"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/12"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }
    static_ports {
        deployment_immediacy = "lazy"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/9"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }
}

## new:

resource "mso_schema_site_anp_epg_bulk_staticport" "static_port" {
    anp_name      = "PROD_AP"
    epg_name      = "EPG1"
    id            = "66b61b98cecea29623726b33/site/616062f8e2a0c43c4efe1bf7/template/E1/anp/PROD_AP/epg/EPG1"
    schema_id     = "66b61b98cecea29623726b33"
    site_id       = "616062f8e2a0c43c4efe1bf7"
    template_name = "E1"

    static_ports {
        deployment_immediacy = "lazy"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/8"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }
    static_ports {
        deployment_immediacy = "lazy"
        fex                  = "101"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/12"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }
    static_ports {
        deployment_immediacy = "lazy"
        fex                  = "101"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/21"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }
    static_ports {
        deployment_immediacy = "lazy"
        leaf                 = "101"
        micro_seg_vlan       = 0
        mode                 = "regular"
        path                 = "eth1/9"
        path_type            = "port"
        pod                  = "pod-1"
        vlan                 = 1000
    }
}
```

### Expected Behavior

When ports get updated or reordered, and port that had fex configuration moves to another block, fex id follow it, but should be cleared for the new port

### Actual Behavior

Port has stale fex id configuration that belonged to different port (in example 1/9 should be configured with no fex as no fex is provided)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by akinross**
fixes #311

### CODE REVIEW

**Review by gmicol — DISMISSED** [review]
LGTM

File: mso/resource_mso_schema_site_anp_epg_bulk_staticport.go [hunk 1]
```diff
@@ -504,6 +524,8 @@ func resourceMSOSchemaSiteAnpEpgBulkStaticPortUpdate(d *schema.ResourceData, m i
 
 			if staticPortMap["type"] == "port" && static_port_fex != "" {
 				portpath = fmt.Sprintf("topology/%s/paths-%s/extpaths-%s/pathep-[%s]", static_port_pod, static_port_leaf, static_port_fex, static_port_path)
+			} else if staticPortMap["type"] == "vpc" && static_port_fex != "" {
+				portpath = fmt.Sprintf("topology/%s/protpaths-%s/extprotpaths-%s/pathep-[%s]", static_port_pod, static_port_leaf, static_port_fex, static_port_path)
```
Comment (samiib) [inline mso/resource_mso_schema_site_anp_epg_bulk_staticport.go:528]: Would it be possible to move setting the port path string into a function? Looks like its mostly duplicated.
Or alternatively moving the strings into constants.

**Review by samiib — CHANGES_REQUESTED** [review]

File: mso/resource_mso_schema_site_anp_epg_bulk_staticport.go (hunk 1 above)
Comment (akinross) [reply mso/resource_mso_schema_site_anp_epg_bulk_staticport.go:528]: I kept it inline with the current code. 

I think there are plenty of code changes that could be made which would reduce duplication in this resource, and would apply to almost all the other schema related resources. I do not think we should address these rewrites in this PR but should do as separate issues when we decide what the next steps will be for the provider.

Comment (shrsr) [reply mso/resource_mso_schema_site_anp_epg_bulk_staticport.go:528]: I agree with @akinross here. A separate PR would be better if we want to bring in radical changes to the resources

**Review by shrsr — DISMISSED** [review]
LGTM

File: mso/resource_mso_schema_site_anp_epg_bulk_staticport.go (hunk 1 above)
Comment (samiib) [reply mso/resource_mso_schema_site_anp_epg_bulk_staticport.go:528]: I had a chat with Akini about this requested change. I am not suggesting to refactor everything to reduce code duplication as this would not be practical. However, I think small incremental refactors around the areas being changed are possible when you are already in context and testing it.
If we are going to be making broader changes to this provider then I am okay to approve.

**Review by samiib — DISMISSED** [review]

**Comment by akinross** [comment]
Remove the logic for the fex vpc issue, and will create a new PR for this. Think datasource and single equivalent resource/datasource should also be adjusted

**Review by samiib — COMMENTED** [review]
LGTM

**Review by samiib — APPROVED** [review]

**Review by gmicol — APPROVED** [review]
LGTM
